const ParameterSeed = [
  {
    parameterName: "물주기",
    type: 1,
    color: "#59B1C9",
    description: "조금, 중간, 많이",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "스프레이",
    type: 0,
    color: "#A1D8CB",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "흙상태",
    type: 1,
    color: "#9E5743",
    description: "건조함, 촉촉함, 축축함",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "영양제",
    type: 0,
    color: "#FFD118",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "순지르기 ",
    type: 0,
    color: "#D5E4AC",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "가지치기",
    type: 0,
    color: "#D0B094",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "거름",
    type: 0,
    color: "#D7AF44",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "비료",
    type: 0,
    color: "#D7AF44",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "퇴비",
    type: 0,
    color: "#D7AF44",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "개화",
    type: 0,
    color: "#F69A9F",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "열매",
    type: 0,
    color: "#F37669",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "식물상태",
    type: 1,
    color: "#6DC49C",
    description: "시들시들, 보통, 좋음",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "잎 색",
    type: 1,
    color: "#D0DE52",
    description: "노랑, 연두, 초록",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "해충",
    type: 0,
    color: "#CDCFC2",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "깍지벌레",
    type: 0,
    color: "#CDCFC2",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "진딧물",
    type: 0,
    color: "#CDCFC2",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "뿌리파리",
    type: 0,
    color: "#CDCFC2",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    parameterName: "응애",
    type: 0,
    color: "#CDCFC2",
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
];

export default ParameterSeed;
